"""Add missing P11 columns

Revision ID: aad3bec4a4fc
Revises: 003
Create Date: 2026-07-23 16:14:07.781805
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aad3bec4a4fc'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytics_performance_dashboards')
    op.drop_table('strategic_strategy_reviews')
    op.drop_table('pmo_change_requests')
    op.drop_table('pmo_follow_up_meetings')
    op.drop_table('training_plans')
    op.drop_table('hr_performance_evaluations')
    op.drop_table('strategic_quality_policies')
    op.drop_table('infra_incident_reports')
    op.drop_table('cx_nps_surveys')
    op.drop_table('procurement_receiving_reports')
    op.drop_table('training_video_tutorials')
    op.drop_table('analytics_performance_data_records')
    op.drop_table('hr_job_descriptions')
    op.drop_table('hr_individual_development_plans')
    op.drop_table('cx_satisfaction_reports')
    op.drop_table('infra_sla_agreements')
    op.drop_table('procurement_supplier_evaluations')
    op.drop_table('infra_continuity_plans')
    op.drop_table('analytics_performance_indicators')
    op.drop_table('strategic_quality_objectives')
    op.drop_table('pmo_execution_plans')
    op.drop_table('procurement_purchase_requests')
    op.drop_table('tech_risk_matrices')
    op.drop_table('training_evaluations')
    op.drop_table('procurement_supplier_registrations')
    op.drop_table('tech_technical_specs')
    op.drop_table('strategic_management_reviews')
    op.drop_table('strategic_qms_scope')
    op.drop_table('hr_induction_checklists')
    op.drop_table('analytics_trend_analysis_reports')
    op.drop_table('infra_maintenance_records')
    op.drop_table('procurement_supplier_performance_reports')
    op.drop_table('training_courses')
    op.drop_table('infra_security_incidents')
    op.drop_table('infra_requests')
    op.drop_table('hr_personnel_requests')
    op.drop_table('tech_release_plans')
    op.drop_table('analytics_kpi_reports')
    op.drop_table('tech_product_roadmaps')
    op.drop_table('procurement_supplier_register')
    op.drop_table('strategic_marketing_plans')
    op.drop_table('tech_deployment_records')
    op.drop_table('infra_availability_reports')
    op.drop_table('training_certification_records')
    op.drop_table('pmo_closure_records')
    op.drop_table('training_user_manuals')
    op.drop_table('tech_uat_signoffs')
    op.drop_table('training_competency_matrices')
    op.drop_table('pmo_handover_acceptances')
    op.drop_table('hr_labor_incidents')
    op.drop_table('cx_csat_surveys')
    op.drop_table('pmo_projects')
    op.drop_table('pmo_weekly_reports')
    op.drop_table('training_attendance_records')
    op.drop_table('cx_exit_interviews')
    op.drop_table('training_sessions')
    op.drop_table('training_needs_assessments')
    op.drop_table('hr_staff_register')
    op.drop_table('tech_solution_sunsets')
    op.drop_table('pmo_deliverables_checklists')
    op.drop_table('cx_complaint_register')
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_username'), table_name='auth_users')
    op.drop_table('auth_users')
    op.drop_table('tech_qa_test_reports')
    op.drop_table('cx_ces_surveys')
    op.drop_table('cx_complaints')
    op.drop_table('hr_competency_assessments')
    op.alter_column('commercial_contracts', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'SUSPENDED', 'COMPLETED', 'TERMINATED', name='contractstatus'),
               existing_nullable=False)
    op.create_index(op.f('ix_commercial_contracts_contract_number'), 'commercial_contracts', ['contract_number'], unique=True)
    op.drop_column('commercial_contracts', 'deleted_at')
    op.drop_column('commercial_contracts', 'is_deleted')
    op.create_index(op.f('ix_commercial_leads_company'), 'commercial_leads', ['company'], unique=False)
    op.drop_column('commercial_leads', 'deleted_at')
    op.drop_column('commercial_leads', 'is_deleted')
    op.alter_column('commercial_proposals', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DRAFT', 'SENT', 'NEGOTIATION', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='proposalstatus'),
               existing_nullable=False)
    op.drop_column('commercial_proposals', 'deleted_at')
    op.drop_column('commercial_proposals', 'is_deleted')
    op.alter_column('commercial_service_churn', 'category',
               existing_type=sa.TEXT(),
               type_=sa.Enum('SCOPE_CREEP', 'BUDGET_OVERRUN', 'TIMELINE_ISSUES', 'QUALITY_CONCERNS', 'RELATIONSHIP_BREAKDOWN', 'STRATEGIC_SHIFT', 'OTHER', name='servicechurncategory'),
               existing_nullable=False)
    op.alter_column('commercial_service_churn', 'retention_attempts',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('commercial_service_churn', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('quality_audit_checklist', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('quality_audits', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_quality_audits_code'), 'quality_audits', ['code'], unique=True)
    op.alter_column('quality_corrective_actions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_quality_corrective_actions_code'), 'quality_corrective_actions', ['code'], unique=True)
    op.alter_column('quality_documents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_quality_documents_code'), 'quality_documents', ['code'], unique=True)
    op.alter_column('quality_improvements', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_quality_improvements_code'), 'quality_improvements', ['code'], unique=True)
    op.alter_column('quality_non_conformities', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_quality_non_conformities_code'), 'quality_non_conformities', ['code'], unique=True)
    op.alter_column('quality_process_owners', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quality_process_owners', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_quality_non_conformities_code'), table_name='quality_non_conformities')
    op.alter_column('quality_non_conformities', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_quality_improvements_code'), table_name='quality_improvements')
    op.alter_column('quality_improvements', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_quality_documents_code'), table_name='quality_documents')
    op.alter_column('quality_documents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_quality_corrective_actions_code'), table_name='quality_corrective_actions')
    op.alter_column('quality_corrective_actions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_quality_audits_code'), table_name='quality_audits')
    op.alter_column('quality_audits', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('quality_audit_checklist', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('commercial_service_churn', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('commercial_service_churn', 'retention_attempts',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('commercial_service_churn', 'category',
               existing_type=sa.Enum('SCOPE_CREEP', 'BUDGET_OVERRUN', 'TIMELINE_ISSUES', 'QUALITY_CONCERNS', 'RELATIONSHIP_BREAKDOWN', 'STRATEGIC_SHIFT', 'OTHER', name='servicechurncategory'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('commercial_proposals', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('commercial_proposals', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('commercial_proposals', 'status',
               existing_type=sa.Enum('DRAFT', 'SENT', 'NEGOTIATION', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='proposalstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.add_column('commercial_leads', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('commercial_leads', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_commercial_leads_company'), table_name='commercial_leads')
    op.add_column('commercial_contracts', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('commercial_contracts', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_commercial_contracts_contract_number'), table_name='commercial_contracts')
    op.alter_column('commercial_contracts', 'status',
               existing_type=sa.Enum('ACTIVE', 'SUSPENDED', 'COMPLETED', 'TERMINATED', name='contractstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_table('hr_competency_assessments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('assessed_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('required_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('has_gap', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('assessed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_staff_register.id'], name=op.f('hr_competency_assessments_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('hr_competency_assessments_pkey'))
    )
    op.create_table('cx_complaints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('customer_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('COMPLAINT', 'CLAIM', name='complainttype'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('desired_outcome', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('OPEN', 'INVESTIGATING', 'RESOLVED', 'CLOSED', name='complaintstatus'), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('escalation_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nc_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cx_complaints_pkey'))
    )
    op.create_table('cx_ces_surveys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('customer_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('responded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cx_ces_surveys_pkey'))
    )
    op.create_table('tech_qa_test_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('release_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('test_type', postgresql.ENUM('UNIT', 'INTEGRATION', 'E2E', 'REGRESSION', name='testtype'), autoincrement=False, nullable=False),
    sa.Column('total_tests', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('passed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blocked', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('report_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'FINAL', name='reportstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['tech_release_plans.id'], name=op.f('tech_qa_test_reports_release_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tech_qa_test_reports_pkey'))
    )
    op.create_table('auth_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_users_pkey'))
    )
    op.create_index(op.f('ix_auth_users_username'), 'auth_users', ['username'], unique=True)
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    op.create_table('cx_complaint_register',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('registered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('resolution_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['cx_complaints.id'], name=op.f('cx_complaint_register_complaint_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cx_complaint_register_pkey')),
    sa.UniqueConstraint('complaint_id', name=op.f('cx_complaint_register_complaint_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('pmo_deliverables_checklists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'COMPLETED', name='checkliststatus'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['pmo_projects.id'], name=op.f('pmo_deliverables_checklists_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pmo_deliverables_checklists_pkey')),
    sa.UniqueConstraint('project_id', name=op.f('pmo_deliverables_checklists_project_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('tech_solution_sunsets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('product', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('sunset_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('migration_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PLANNED', 'IN_PROGRESS', 'COMPLETED', name='sunsetstatus'), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tech_solution_sunsets_pkey'))
    )
    op.create_table('hr_staff_register',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hire_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('contract_type', postgresql.ENUM('PERMANENT', 'CONTRACTOR', 'INTERN', name='hr_contract_type'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'TERMINATED', 'ON_LEAVE', name='staffstatus'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('hr_staff_register_pkey'))
    )
    op.create_table('training_needs_assessments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('employee_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('skills_gap', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='needpriority'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('IDENTIFIED', 'IN_REVIEW', 'APPROVED', 'COMPLETED', name='needstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('training_needs_assessments_pkey'))
    )
    op.create_table('training_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('instructor', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('attendees', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='sessionstatus'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['training_courses.id'], name=op.f('training_sessions_course_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('training_sessions_pkey'))
    )
    op.create_table('cx_exit_interviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('churn_reason_category', postgresql.ENUM('PRICE', 'PRODUCT_FIT', 'SUPPORT', 'PERFORMANCE', 'COMPETITOR', 'OTHER', name='churnreasoncategory'), autoincrement=False, nullable=False),
    sa.Column('detailed_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('would_return', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('interview_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cx_exit_interviews_pkey'))
    )
    op.create_table('training_attendance_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('participant_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hours_attended', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('signed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], name=op.f('training_attendance_records_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('training_attendance_records_pkey'))
    )
    op.create_table('pmo_weekly_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accomplishments', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('next_week_plan', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blockers', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status_percent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pmo_projects.id'], name=op.f('pmo_weekly_reports_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pmo_weekly_reports_pkey'))
    )
    op.create_table('pmo_projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_line', postgresql.ENUM('SERVICIOS', 'SAAS', name='productline'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('KICKED_OFF', 'IN_EXECUTION', 'CLOSED', 'ON_HOLD', name='projectstatus'), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('budget', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('project_manager', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['commercial_contracts.id'], name=op.f('pmo_projects_contract_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pmo_projects_pkey'))
    )
    op.create_table('cx_csat_surveys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('customer_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('responded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cx_csat_surveys_pkey'))
    )
    op.create_table('hr_labor_incidents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('employee_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('incident_type', postgresql.ENUM('WARNING', 'ACCIDENT', 'VIOLATION', 'GRIEVANCE', name='incidenttype'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resolution', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('OPEN', 'RESOLVED', 'CLOSED', name='hr_incident_status'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('hr_labor_incidents_pkey'))
    )
    op.create_table('pmo_handover_acceptances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accepted_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('accepted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('warranty_period_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'SIGNED', name='handoverstatus'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pmo_projects.id'], name=op.f('pmo_handover_acceptances_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pmo_handover_acceptances_pkey')),
    sa.UniqueConstraint('project_id', name=op.f('pmo_handover_acceptances_project_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('training_competency_matrices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('competencies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('training_competency_matrices_pkey'))
    )
    op.create_table('tech_uat_signoffs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('release_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('signed_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('signed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'SIGNED', 'REJECTED', name='uatstatus'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['tech_release_plans.id'], name=op.f('tech_uat_signoffs_release_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tech_uat_signoffs_pkey'))
    )
    op.create_table('training_user_manuals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('product', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('content_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', name='manualstatus'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('training_user_manuals_pkey'))
    )
    op.create_table('pmo_closure_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('lessons_learned', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('final_budget', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('customer_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('OPEN', 'CLOSED', name='closurestatus'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pmo_projects.id'], name=op.f('pmo_closure_records_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pmo_closure_records_pkey')),
    sa.UniqueConstraint('project_id', name=op.f('pmo_closure_records_project_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('training_certification_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('participant_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('certificate_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expires_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'EXPIRED', 'REVOKED', name='certstatus'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['training_courses.id'], name=op.f('training_certification_records_course_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('training_certification_records_pkey')),
    sa.UniqueConstraint('certificate_code', name=op.f('training_certification_records_certificate_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('infra_availability_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('uptime_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('downtime_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sla_met', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('infra_availability_reports_pkey'))
    )
    op.create_table('tech_deployment_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('release_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('environment', postgresql.ENUM('DEV', 'STAGING', 'PRODUCTION', name='deploymentenvironment'), autoincrement=False, nullable=False),
    sa.Column('deployed_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('deployed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('rollback_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('SUCCESS', 'FAILED', 'ROLLED_BACK', name='deploymentstatus'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['tech_release_plans.id'], name=op.f('tech_deployment_records_release_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tech_deployment_records_pkey'))
    )
    op.create_table('strategic_marketing_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goals', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('budget', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('activities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'ACTIVE', 'COMPLETED', name='marketingplanstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('strategic_marketing_plans_pkey'))
    )
    op.create_table('procurement_supplier_register',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['procurement_supplier_registrations.id'], name=op.f('procurement_supplier_register_supplier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('procurement_supplier_register_pkey')),
    sa.UniqueConstraint('supplier_id', name=op.f('procurement_supplier_register_supplier_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('tech_product_roadmaps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('product_line', postgresql.ENUM('SERVICIOS', 'SAAS', name='productline'), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vision', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('strategic_goals', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', name='roadmapstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tech_product_roadmaps_pkey'))
    )
    op.create_table('analytics_kpi_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('indicators_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_kpi_reports_pkey'))
    )
    op.create_table('tech_release_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('product', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('planned_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('actual_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PLANNED', 'IN_PROGRESS', 'DEPLOYED', 'ROLLED_BACK', name='releasestatus'), autoincrement=False, nullable=False),
    sa.Column('release_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tech_release_plans_pkey'))
    )
    op.create_table('hr_personnel_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('requested_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('justification', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('budget', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'FILLED', name='personnelrequeststatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('hr_personnel_requests_pkey'))
    )
    op.create_table('infra_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('requester', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('specification', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('justification', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('SUBMITTED', 'APPROVED', 'PROVISIONED', 'REJECTED', name='requeststatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('infra_requests_pkey'))
    )
    op.create_table('infra_security_incidents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('incident_type', postgresql.ENUM('BREACH', 'MALWARE', 'PHISHING', 'UNAUTHORIZED_ACCESS', 'OTHER', name='securityincidenttype'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('impact', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('containment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'INVESTIGATING', 'RESOLVED', 'CLOSED', name='securityincidentstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('infra_security_incidents_pkey'))
    )
    op.create_table('training_courses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('modality', postgresql.ENUM('ONLINE', 'PRESENTIAL', 'HYBRID', name='coursemodality'), autoincrement=False, nullable=False),
    sa.Column('duration_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', name='coursestatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('training_courses_pkey'))
    )
    op.create_table('procurement_supplier_performance_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('avg_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('on_time_delivery_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quality_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['procurement_supplier_registrations.id'], name=op.f('procurement_supplier_performance_reports_supplier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('procurement_supplier_performance_reports_pkey'))
    )
    op.create_table('infra_maintenance_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('maintenance_type', postgresql.ENUM('PREVENTIVE', 'CORRECTIVE', 'UPGRADE', name='maintenancetype'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('completed_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('performed_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', name='maintenancestatus'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('infra_maintenance_records_pkey'))
    )
    op.create_table('analytics_trend_analysis_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('indicator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('trend', postgresql.ENUM('UP', 'DOWN', 'FLAT', 'VOLATILE', name='trenddirection'), autoincrement=False, nullable=False),
    sa.Column('change_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('insights', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommendations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['analytics_performance_indicators.id'], name=op.f('analytics_trend_analysis_reports_indicator_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_trend_analysis_reports_pkey'))
    )
    op.create_table('hr_induction_checklists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hire_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'COMPLETED', name='inductioncheckliststatus'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('hr_induction_checklists_pkey'))
    )
    op.create_table('strategic_qms_scope',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('scope_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('exclusions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('applicable_normative', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_current', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('strategic_qms_scope_pkey'))
    )
    op.create_table('strategic_management_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('review_period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('review_period_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('prepared_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('conclusions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('report_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('strategic_management_reviews_pkey'))
    )
    op.create_table('tech_technical_specs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'REVIEWED', 'APPROVED', name='specstatus'), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tech_technical_specs_pkey'))
    )
    op.create_table('procurement_supplier_registrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('services', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='supplierstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('procurement_supplier_registrations_pkey'))
    )
    op.create_table('training_evaluations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('participant', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], name=op.f('training_evaluations_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('training_evaluations_pkey'))
    )
    op.create_table('tech_risk_matrices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('risks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tech_risk_matrices_pkey'))
    )
    op.create_table('procurement_purchase_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('requester', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('estimated_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('justification', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'ORDERED', name='purchaserequeststatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('procurement_purchase_requests_pkey'))
    )
    op.create_table('pmo_execution_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phases', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('milestones', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('risks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'APPROVED', name='pmo_plan_status'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pmo_projects.id'], name=op.f('pmo_execution_plans_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pmo_execution_plans_pkey'))
    )
    op.create_table('strategic_quality_objectives',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('objective', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('process_code', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('target_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('actual_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metric_unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ON_TRACK', 'AT_RISK', 'BEHIND', 'ACHIEVED', name='objectivestatus'), autoincrement=False, nullable=False),
    sa.Column('responsible', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('strategic_quality_objectives_pkey'))
    )
    op.create_table('analytics_performance_indicators',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('process_code', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('formula', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('frequency', postgresql.ENUM('MONTHLY', 'QUARTERLY', 'YEARLY', name='frequency'), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_performance_indicators_pkey'))
    )
    op.create_table('infra_continuity_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('last_reviewed', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('risk_assessment', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('recovery_strategies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'REVIEWED', 'APPROVED', name='continuityplanstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('infra_continuity_plans_pkey'))
    )
    op.create_table('procurement_supplier_evaluations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('evaluator', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('criteria_scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('total_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('period', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'COMPLETED', name='proc_evaluation_status'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['procurement_supplier_registrations.id'], name=op.f('procurement_supplier_evaluations_supplier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('procurement_supplier_evaluations_pkey'))
    )
    op.create_table('infra_sla_agreements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('uptime_target', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('response_time_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resolution_time_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'EXPIRED', 'TERMINATED', name='slastatus'), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('infra_sla_agreements_pkey'))
    )
    op.create_table('cx_satisfaction_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nps_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('csat_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ces_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('complaints_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recommendations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cx_satisfaction_reports_pkey'))
    )
    op.create_table('hr_individual_development_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('goals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('courses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('review_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'COMPLETED', name='idpstatus'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('hr_individual_development_plans_pkey'))
    )
    op.create_table('hr_job_descriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('reports_to', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('responsibilities', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('requirements', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('competencies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('hr_job_descriptions_pkey'))
    )
    op.create_table('analytics_performance_data_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('indicator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('recorded_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['analytics_performance_indicators.id'], name=op.f('analytics_performance_data_records_indicator_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_performance_data_records_pkey'))
    )
    op.create_table('training_video_tutorials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', name='videostatus'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['training_courses.id'], name=op.f('training_video_tutorials_course_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('training_video_tutorials_pkey'))
    )
    op.create_table('procurement_receiving_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('purchase_request_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('received_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('received_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('condition_ok', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['procurement_purchase_requests.id'], name=op.f('procurement_receiving_reports_purchase_request_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('procurement_receiving_reports_pkey'))
    )
    op.create_table('cx_nps_surveys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('customer_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('PROMOTER', 'PASSIVE', 'DETRACTOR', name='npscategory'), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('responded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cx_nps_surveys_pkey'))
    )
    op.create_table('infra_incident_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('severity', postgresql.ENUM('P1', 'P2', 'P3', 'P4', name='incidentseverity'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('root_cause', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolution', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('OPEN', 'INVESTIGATING', 'RESOLVED', 'CLOSED', name='incidentstatus'), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('infra_incident_reports_pkey'))
    )
    op.create_table('strategic_quality_policies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'REVIEWED', 'APPROVED', 'OBSOLETE', name='policystatus'), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('strategic_quality_policies_pkey'))
    )
    op.create_table('hr_performance_evaluations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('evaluator', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('strengths', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('improvements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'COMPLETED', name='evaluationstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('hr_performance_evaluations_pkey'))
    )
    op.create_table('training_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('courses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('budget', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'ACTIVE', 'COMPLETED', name='planstatus'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('training_plans_pkey'))
    )
    op.create_table('pmo_follow_up_meetings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('minutes', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('action_items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('next_meeting_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['pmo_projects.id'], name=op.f('pmo_follow_up_meetings_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pmo_follow_up_meetings_pkey'))
    )
    op.create_table('pmo_change_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('impact_analysis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('SUBMITTED', 'APPROVED', 'REJECTED', name='crstatus'), autoincrement=False, nullable=False),
    sa.Column('requested_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pmo_projects.id'], name=op.f('pmo_change_requests_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pmo_change_requests_pkey'))
    )
    op.create_table('strategic_strategy_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('reviewed_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('decisions', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('next_review_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('strategic_strategy_reviews_pkey'))
    )
    op.create_table('analytics_performance_dashboards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('layout', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('filters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_performance_dashboards_pkey'))
    )
    # ### end Alembic commands ###
